#
#   _   _   _   _____   _   _   _____   _   _   _____
#   | | | | | | /  ___/ | | | | /  _  \ | | | | |_   _|
#   | | | | | | | |___  | |_| | | | | | | | | |   | |
#   | | | | | | \___  \ |  _  | | | | | | | | |   | |
#   | |_| | | |  ___| | | | | | | |_| | | |_| |   | |
#   \_____/ |_| /_____/ |_| |_| \_____/ \_____/   |_|
#

server:
  name: "测试服务器"
  host: "127.0.0.1"
  port: 25633

msg: "&7[&e喊话&7]&f[${ip}]&r${name} &d>> &r${msg}"
