#
#   _   _   _   _____   _   _   _____   _   _   _____
#   | | | | | | /  ___/ | | | | /  _  \ | | | | |_   _|
#   | | | | | | | |___  | |_| | | | | | | | | |   | |
#   | | | | | | \___  \ |  _  | | | | | | | | |   | |
#   | |_| | | |  ___| | | | | | | |_| | | |_| |   | |
#   \_____/ |_| /_____/ |_| |_| \_____/ \_____/   |_|
#

server:
  host: "127.0.0.1"
  port: 25633
